apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: gamma-

commonLabels:
  environment: gamma

patches:
  - path: replica-patch.yaml

configMapGenerator:
  - name: SERVICE_NAME-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
